version: "3.0"

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: ultra
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data

  server:
    build: .
    restart: always
    ports:
      - 3000:3000
